var g;function h(b){var c=0;return function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}}}function l(b){var c="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return c?c.call(b):{next:h(b)}}function m(b){if(!(b instanceof Array)){b=l(b);for(var c,d=[];!(c=b.next()).done;)d.push(c.value);b=d}return b}var n="function"==typeof Object.create?Object.create:function(b){function c(){}c.prototype=b;return new c},p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var r={l:!0},t={};try{t.__proto__=r;q=t.l;break a}catch(b){}q=!1}p=q?function(b,c){b.__proto__=c;if(b.__proto__!==c)throw new TypeError(b+" is not extensible");return b}:null}var v=p,w="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){b!=Array.prototype&&b!=Object.prototype&&(b[c]=d.value)};
function x(b){b=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,b];for(var c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}return globalThis}var y=x(this);function z(b,c){if(c){var d=y;b=b.split(".");for(var e=0;e<b.length-1;e++){var f=b[e];f in d||(d[f]={});d=d[f]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&w(d,b,{configurable:!0,writable:!0,value:c})}}
z("Object.entries",function(b){return b?b:function(c){var d=[],e;for(e in c)Object.prototype.hasOwnProperty.call(c,e)&&d.push([e,c[e]]);return d}});var A={};Object.defineProperty(A,"__esModule",{value:!0});function B(b,c){if(!b)throw"type is required.";if("string"!==typeof b)throw"type must be string.";if("undefined"===typeof c[b])throw"Store: "+b+" isn't existed. Please create it with create(\""+b+'")';}var C;
if("undefined"!==typeof window){var D=function(){var b=EventTarget.call(this)||this;b.a={};b.store={};b.c=[];b.f=void 0;return b},E=EventTarget;D.prototype=n(E.prototype);D.prototype.constructor=D;if(v)v(D,E);else for(var F in E)if("prototype"!=F)if(Object.defineProperties){var G=Object.getOwnPropertyDescriptor(E,F);G&&Object.defineProperty(D,F,G)}else D[F]=E[F];g=D.prototype;g.create=function(b,c){c=void 0===c?{}:c;if("undefined"!==typeof this.store[b])throw b+" is already existed.";this.a[b]=new Event(b);
this.store[b]=this.b("undefined"!==typeof c?c:{},"create",b);return this.store[b]};g.get=function(b){B(b,this.a);return Object.freeze(this.b(this.store[b],"get",b))};g.set=function(b,c){B(b,this.a);var d=this.a[b];d.detail=c;this.store[b]=this.b(c,"set",b);this.dispatchEvent(d);return this.store[b]};g.i=function(b,c){var d=this;"*"===b&&(b=m(this.h()).concat()||[]);"string"===typeof b&&(b=Array(b));var e=[];b.forEach(function(f){function k(){return c(d.b(d.store[f],"subscribe",f),f,d.g())}B(f,d.a);
e.push(k);return d.addEventListener(f,function(){return k()})});return{unsubscribe:function(){return Object.entries(d.a).forEach(function(f,k){f=l(f);var u=f.next().value;f.next();return d.removeEventListener(u,e[k])})}}};g.h=function(){return Object.keys(this.store)};g.g=function(){var b=this,c=[];Object.entries(this.store).map(function(d){var e=l(d);d=e.next().value;e=e.next().value;c.push(JSON.parse('{"name":"'+d+'","store":'+JSON.stringify(b.b(e,"get",d))+"}"))});return c};g.b=function(b,c,d){var e=
this;b=void 0===b?this.store:b;var f=Object.freeze(b);this.c.map(function(k){return f=k(f,c,d)});this.f&&"undefined"===typeof window.a&&(window.a={version:"0.4.0",listener:function(k){return e.i("*",function(u){return k(u)})},j:[]},"subscribe"!==c&&window.a.j.push({name:d,j:c,store:b}));return f};C=D}else{var H=function(){this.a={};this.store={};this.c=[];this.f=void 0};g=H.prototype;g.create=function(b,c){return c=void 0===c?{}:c};g.get=function(){return{}};g.set=function(){return{}};g.i=function(){return{unsubscribe:function(){return null}}};
g.h=function(){return[]};g.g=function(){return[]};C=H}A.default=C;
